### ISSUE TITLE
Unexpected behavior with CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by tilsche** [score-p/scorep_plugin_libsensors#1]
User-provided `CMAKE_INSTALL_PREFIX` is ignored.

This line seems wrong and should probably just go.

https://github.com/score-p/scorep_plugin_libsensors/blob/master/CMakeLists.txt#L15

I don't really want to open the rest of the can-of-CMake-worms...

**Comment by rschoene** [comment]
Fixed with b1ec8a52bdb60579c275f4a69c2562043ae7043b
