### ISSUE TITLE
Race condition in fini()

### ISSUE THREAD

**Issue by cvonelm** [score-p/scorep_plugin_libsensors#2]
The plugin seems to have an issue with thread/process safety. For the same workload:

1. Running without the plugin and multiple processes (mpirun -n 2 for example) works fine
2. Running with the plugin and one process (mpirun -n 1) works fine.
3. Running with the plugin and multiple processes (mpirun -n 2) crashes in `fini()`.

Sadly, I could not throw gdb at the problem as the program refuses to start under gdb.

This MPI Hello World suffices to trigger the segfault: https://mpitutorial.com/tutorials/mpi-hello-world/
Compiler used: icc (2021.10.0)
Compiler invocation: `scorep mpiicc hello_world.c -o hello_world`
Program invocation: `mpirun -n 2 ./hello world`

**Comment by rschoene** [comment]
Fixed in ef84c97
Was no race condition, but the use of an uninitialized variable when no sensor was added...
